[Corne] Force set userdata size due to errors
Otherwise we get this shit, for absolutely no reason:

 | In function 'eeconfig_read_user_datablock.constprop',
 |     inlined from 'keyboard_pre_init_user' at
/__w/qmk_userspace/qmk_userspace/users/drashna/callbacks.c:49:5,
 |     inlined from 'keyboard_pre_init_kb' at quantum/keyboard.c:286:5,
 |     inlined from 'keyboard_setup' at quantum/keyboard.c:323:5,
 |     inlined from 'main' at quantum/main.c:41:5:
 | quantum/eeconfig.c:321:9: error: 'memset' writing 64 bytes into a
region of size 14 overflows the destination [-Werror=stringop-overflow=]
 |          memset(data, 0, (EECONFIG_USER_DATA_SIZE));
 |          ^